### ISSUE TITLE
macOS compiling ?

### ISSUE THREAD

**Issue by azoreseuropa** [libretro-mirrors/mednafen-git#12]
What about compile mednafen to macOS ? I have macOS and I would like to compile it, please ?

**Comment by azoreseuropa** [comment]
Hello ? I compiled several emulators thanks to the developers helped me step by step and I wrote the tutor how to do that. I want your mednafen to be next one on my list. I love your emulator for Windows but I want to use it for macOS and glad to share the emulator with macOS users in your site. Help?

**Comment by azoreseuropa** [comment]
Hello ? You there ? Been 14 days ago now.

**Comment by twinaphex** [comment]
I don't think you understand what this repository is. It's not headed by the Mednafen author or anything. It's just meant for pulling in source code changes.
